# Generated by Django 3.1.7 on 2021-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('1', 'HR Management Software'), ('2', 'Cloud & SaaS'), ('3', 'CMMS Software'), ('4', 'Telecommunications Management'), ('5', 'ERP Software')], max_length=100, null=True),
        ),
    ]
