# Generated by Django 3.1.7 on 2021-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210426_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.CharField(choices=[('HR Management Software', 'HR Management Software'), ('Cloud & SaaS', 'Cloud & SaaS'), ('CMMS Software', 'CMMS Software'), ('Telecommunications Management', 'Telecommunications Management'), ('ERP Software', 'ERP Software')], max_length=100, null=True),
        ),
    ]
