# Generated by Django 3.1.7 on 2021-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
