# Generated by Django 3.1.7 on 2021-04-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='gender',
            new_name='male',
        ),
        migrations.AddField(
            model_name='employee',
            name='female',
            field=models.BooleanField(null=True),
        ),
    ]
