# Generated by Django 3.1.7 on 2021-04-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
