# Generated by Django 3.1.7 on 2021-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210425_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default='00.00'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skillset',
            field=models.CharField(choices=[('Web Developer,', 'Web Developer'), ('Web Designer,', 'Web Designer'), ('.py, ', 'Python'), ('.java,', 'JAVA'), ('Wordpress,', 'Wordpress'), ('.php,', 'PHP'), ('.NET,', '.NET'), ('mysql,', 'MYSQL')], default='', max_length=100),
        ),
    ]
