# Generated by Django 3.1.7 on 2021-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210423_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='female',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='male',
        ),
        migrations.AddField(
            model_name='employee',
            name='checkgender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=15),
        ),
    ]
