# Generated by Django 3.1.7 on 2021-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210425_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='skillset',
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.BooleanField(default='False'),
        ),
    ]
