# Generated by Django 3.1.7 on 2021-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210427_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='checkgender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=15),
        ),
    ]
