# Generated by Django 3.1.7 on 2021-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20210427_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='checkgender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], default='MALE', max_length=15),
        ),
    ]
