# Generated by Django 3.1.7 on 2021-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20210427_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='checkgender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=15),
        ),
    ]
