# Generated by Django 3.1.7 on 2021-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20210427_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='checkgender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], default='M', max_length=15),
        ),
    ]
